version: "2.4"

services:
        php-apache:
                build:
                        context: ./apache-php
                        target: prod
                ports:
                        - 80:80  
                volumes:
                        - ./apache-php/MediterPourGrandir/:/var/www/html/   
        mysql:
                image: mysql:5.6.40
                #restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=monsupersite
#                       - MYSQL_USER=root
                        - MYSQL_PASSWORD=root
                ports:
                        - "3306:3306"
                volumes:
                        - mysql-db:/var/lib/mysql
        postfix:
                image: boky/postfix
                environment:
                        - ALLOWED_SENDER_DOMAINS=127.0.0.1
                        # - RELAYHOST=192.168.1.37
                ports: 
                        - "1587:587"         
      
volumes: 
      mysql-db:
