version: "3.2"
services:
  php-apache:
    build:
      context: ./apache-php
    ports:
      - 80:80  
    volumes:
      - ./MediterPourGrandir/:/var/www/html/  
  mysql:
    image: mysql:5.6.40
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=monsupersite
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
        # - /var/www/html/
        #- ./var/www/html/'monsupersite (1).sql':/docker-entrypoint-initdb.d/'monsupersite (1).sql'

   
  postfix:
    build:
      context: ./postFix
    ports:
      - 25:25
    environment:
      POSTFIX_HOSTNAME: "example.com"
      POSTFIX_RELAY_HOST: "example.com:25"
      POSTFIX_RELAY_USER: "user"
      # POSTFIX_RELAY_PASSWORD_FILE: "password" 
      # /run/secrets/postfix_password
      # secrets:
      # - postfix_password
  
  # secrets:
  # bpostfix_password:
  # file: ./stack/secrets/postfix_password.context

volumes: 
      mysql-db:
